version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=68065833
      - POSTGRES_DB=postgres
    volumes:
      - .:/usr/src/app
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
